# Generated by Django 4.1.3 on 2022-11-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_order_price_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
