# Generated by Django 4.1.3 on 2022-11-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
